// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // Use the non-pooling URL for Prisma CLI (migrations, db push, seed)
    // so that DDL statements work correctly. Falls back to DATABASE_URL for
    // local dev. Vercel's Neon integration sets DATABASE_URL_UNPOOLED.
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
